config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "cards#index"
  get '/search' => 'pages#search', :as => 'search_page'
  resources :cards
  resources :majors
  resources :minors
  resources :readings
  resources :nasas
  resource :article, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article
  def make_NYT_API_call
    uri = URI("https://api.nytimes.com/svc/search/v2/articlesearch.json")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    uri.query = URI.encode_www_form({
      "api-key" => ENV['NYT_API_KEY'],
      "q" => "tarot",
      "fl" => "snippet, web_url, headline"
    })
    request = Net::HTTP::Get.new(uri.request_uri)
    api = http.request(request).body
    @result = JSON.parse(api)["response"]["docs"]
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_attached_file :image, styles: {large: "300x435>", medium: "125x250>", thumb: "50x80>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :card_name, :presence => true
  validates :card_content, :presence => true
  validates :suit, :presence => true
  validates :arcana, :presence => true

  def self.threeCards
    @deck = Card.all
    past = @deck.slice(rand(78))
    present = @deck.slice(rand(77))
    future = @deck.slice(rand(76))
    @spread = [past, present, future,]
    if (past === present || past === future || present === future)
      @deck = Card.all
      past = @deck.slice(rand(78))
      present = @deck.slice(rand(77))
      future = @deck.slice(rand(76))
      @list = [past, present, future,]
      return @list
    else
      return @spread
    end
  end

  def self.focusCard
    @deck = Card.all
    @focus = @deck.slice(rand(78))
    return @focus
  end

  def self.oneCard
    @deck = Card.all
    @one = @deck.slice(rand(78))
    return @one
  end

  scope :major_arcana, -> { where(:arcana => 'Major') }

  scope :minor_amazon, -> { where(:suit => 'amazon') }
  scope :minor_microsoft, -> { where(:suit => 'microsoft') }
  scope :minor_google, -> { where(:suit => 'google') }
  scope :minor_oracle, -> { where(:suit => 'oracle') }
end

app/models/nasa.rb
class Nasa < ApplicationRecord
  def self.get_api_info(set_date)
		nasa_api = "https://api.nasa.gov/planetary/apod?api_key=#{ENV['NASA_API_KEY']}&date=#{set_date}"
		request_to_nasa_api = Net::HTTP.get(URI(nasa_api))
		Rails.logger.debug("#{JSON.parse request_to_nasa_api}")
		JSON.parse request_to_nasa_api
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    api_call = Article.new
    @response = api_call.make_NYT_API_call()
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all.order(:id)
    respond_to do |format|
      format.html 
      format.js { render 'cards/index.js.erb'}
      format.js
     end
  end

  def show
    @card = Card.find(params[:id])
    @cards = Card.threeCards()
  end

  def new
    @card = Card.new
  end

  def create
   @card = Card.new(card_params)
   if @card.save
     redirect_to  cards_path
   else
     render :new
   end
 end

 def edit
   @card = Card.find(params[:id])
  end

  def update
    @card= Card.find(params[:id])
    if @card.update(card_params)
      redirect_to cards_path
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end


private
 def card_params
   params.require(:card).permit(:card_name, :card_content, :suit, :arcana, :image)
 end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController

  def index
    @cards = Card.all.order(:id)
    @arcana_major = @cards.major_arcana
    @amazon_minor = @cards.minor_amazon
    @microsoft_minor = @cards.minor_microsoft
    @google_minor = @cards.minor_google
    @oracle_minor = @cards.minor_oracle
  end

end

app/controllers/nasas_controller.rb
class NasasController < ApplicationController
  def index
    @card = Card.oneCard()
  	@nasa_info = Nasa.get_api_info(params[:date] || Time.now.in_time_zone('US/Eastern').to_date.to_s)
  	@media_type_is_video = @nasa_info['media_type'].eql?("video")
  end

  def new
    @card = Card.oneCard()
    @nasa_info = Nasa.get_api_info(params[:date] || Time.now.in_time_zone('US/Eastern').to_date.to_s)
  	@media_type_is_video = @nasa_info['media_type'].eql?("video")
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'nasas/new.js.erb'}
      format.js
     end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Search can't be blank.") and return
    else
      @parameter = params[:search].downcase
      @results = Card.all.where("lower(card_name) LIKE :search", search: @parameter)
    end
  end

end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController

  def index
    @cards = Card.threeCards()
    @focus = Card.focusCard()
    respond_to do |format|
        format.html 
        format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nasa_picture_helper.rb
module NasaPictureHelper
end

app/views/articles/show.html.erb
<div class="well">
  <h4>New York Times</h4>
  <h5>Articles on Tarot</h5>
  <%= image_tag("cards.jpg", :alt => "article", :id => "article_pic") %>
</div>
<div class="row">
  <div class="col s12">
    <ul>
      <% @response.each do |r| %>
        <li><%= link_to r["snippet"], r["web_url"], :target => "_blank" %></li>
      <br>
      <% end %>
  </ul>
  </div>
</div>

app/views/cards/_three.html.erb
<div class="container">
  <div class="section">
    <div class="cards-grid">
      <div class="row">
        <div id="focus-card">
          <div class="col s4 offset-s4 cards-holder">
            <div class="card hoverable">
              <div class="card-image materialboxed" width="50">
                <p><strong><%= link_to @focus.card_name, card_path(@focus) %></strong></p>
                <p><%= image_tag @focus.image.url(:large) %></p>
              </div>
              <div class="card-content mar-bottom">
              </div>
            </div>
            <br><br><br><br><br>
          </div>
        </div>
      </div>
      <div class="row">
        <% @cards.each do |card| %>
        <div class="col s4 l4 m4 cards-holder">
          <div class="card hoverable">
            <div class="card-image materialboxed" width="50">
              <p><strong><%= link_to card.card_name, card_path(card) %></strong></p>
              <p><%= image_tag card.image.url(:large) %></p>
            </div>
            <div class="card-content mar-bottom">
            </div>
          </div>
        </div>
       <% end %>
     </div>
   </div>
  </div>
</div>
<br><br><br>

app/views/cards/index.html.erb
<div id="candle_gif">
  <%= image_tag("giphy.gif", :alt => "candle_gif", :id => "gif") %>
</div>
<div id="enter_btn">
  <%= button_to "Enter Site", { :action => "index" }, :method => :get, remote: true  %>
</div>
<br><br>
<div class="container" id="search_bar">
  <div>
    <%= form_tag(search_page_path, :method => "get",
          class: 'navbar-form navbar-left') do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        <div id="btn">
          <%= button_tag "Card search", :class => 'btn',:name => nil%>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br><br><br>
<div class="row" id="deck_show">
  <div class="col s12">
    <div id="cards-home">
    <% @cards.each do |card| %>
       <%= link_to image_tag(card.image.url(:thumb)), card_path(card) %>
    <% end %>
    </div>
  </div>
</div>



<br><br>
<div class="well" id="ornament_pic">
  <%= image_tag("ornament.png", :alt => "psychic", :id => "filigree_image") %>
</div>
<br><br><br><br>

app/views/cards/index.js.erb
$("#candle_gif").hide();
$("#deck_show").show();
$("#search_bar").show();
$("#ornament_pic").show();
$("#enter_btn").hide();

app/views/cards/show.html.erb
<br><br><br><br>

<div class="row">
  <div class="col s4" id="show-img">
    <h6><%= image_tag @card.image.url(:large) %></h6>
  </div>
  <div class="col s8">
    <h1><%= @card.card_name %></h1>
    <h6><%= @card.card_content %></h6>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>Tech Tarot &copy; 2018</p>
</div>

app/views/layouts/_navbar.html.erb
<nav id="nav_bar">
    <div class="nav-wrapper">
      <li class="brand-logo center" id="logo-center" ><%= link_to 'TECH TAROT', root_path %></li>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to 'ARCANA', majors_path %></li>
        <li><%= link_to 'CARD OF THE DAY', nasas_path %></li>

      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'TAROT READING', readings_path %></li>
        <li><%= link_to 'ARTICLES', article_path %></li>
      </ul>
      <p id="sign-in" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        <%= link_to 'My Account', edit_user_registration_path %> |
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
        <%= link_to 'Login', new_user_session_path %> |
        <%= link_to 'Register', new_user_registration_path %>
        <% end %>
      </p>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTarot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'crystalball.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kavivanar|Old+Standard+TT" rel="stylesheet">
  </head>
  <%= render 'layouts/navbar' %>
  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/majors/index.html.erb
<div id="major-cards">
  <div class="row">
    <div class="col s5">
      <br><br>
      <div class="well">
        <%= image_tag("tower.jpg", :alt => "tower", :id => "tower_image") %>
      </div>
    </div>
    <div class="cols s7">
      <br><br>
      <p>Each card carries a perspective.</p>
      <p>Rediscovery macrobiotic blue whale, cleansing bioneers. Coconut water nonprofit integral ecstatic dance leave no trace channeling cuddle party, heartbeat of our ancestors conflict resolution on the playa. Kundalini folk music dreamwork emotional release craniosacral therapy quantum, community sharing downward dog. Co-op authentic self ancient chinese wisdom alkaline, seaweed tempeh kirtan tofurkey lavender djembe. Bay Area pranayama fire tending flax seed oil five rhythms spiral jade earrings, mercury retrograde reproductive system vitamix combined energy fields cold plunge. Optimal frequency spoken word all-natural sun salutation, tripping on native american ancestry past life yerba matte.</p>
    </div>
  </div>
  <h1> Major Cards </h1>
  <p>Rediscovery macrobiotic blue whale, cleansing bioneers. Coconut water nonprofit integral ecstatic dance leave no trace channeling cuddle party, heartbeat of our ancestors conflict resolution on the playa. Kundalini folk music dreamwork emotional release craniosacral therapy quantum, community sharing downward dog. Co-op authentic self ancient chinese wisdom alkaline, seaweed tempeh kirtan tofurkey lavender djembe. Bay Area pranayama fire tending flax seed oil five rhythms spiral jade earrings, mercury retrograde reproductive system vitamix combined energy fields cold plunge. Optimal frequency spoken word all-natural sun salutation, tripping on native american ancestry past life yerba matte.</p>
  <% @arcana_major.each do |card| %>
      <%= link_to image_tag(card.image.url(:medium)), card_path(card) %>
  <% end %>
</div>
<br>

<div id="minor-cards">
  <h1> Minor Cards </h1>

  <h4>GOOGLE</h4>
  <p>Yoga master reverse osmosis light energy goddess kefir cosmic Dr. Bronner's, to end suffering life coach healing energy essential. Tantra holistic indigo child peacock feather, tapping seasonal. The buddha healer pranayama, forest prayer flags vitamin-rich tripping on enneagram. Bioneers ganesh goji berries, entheogen short-grain brown rice.</p>
    <% @google_minor.each do |card| %>
        <%= link_to image_tag(card.image.url(:thumb)), card_path(card) %>
    <% end %>
    <br>
  <h4>AMAZON</h4>
  <p>Yoga master reverse osmosis light energy goddess kefir cosmic Dr. Bronner's, to end suffering life coach healing energy essential. Tantra holistic indigo child peacock feather, tapping seasonal. The buddha healer pranayama, forest prayer flags vitamin-rich tripping on enneagram. Bioneers ganesh goji berries, entheogen short-grain brown rice.</p>
    <% @amazon_minor.each do |card| %>
        <%= link_to image_tag(card.image.url(:thumb)), card_path(card) %>
    <% end %>
    <br>
  <h4>MICROSOFT</h4>
  <p>Yoga master reverse osmosis light energy goddess kefir cosmic Dr. Bronner's, to end suffering life coach healing energy essential. Tantra holistic indigo child peacock feather, tapping seasonal. The buddha healer pranayama, forest prayer flags vitamin-rich tripping on enneagram. Bioneers ganesh goji berries, entheogen short-grain brown rice.</p>
    <% @microsoft_minor.each do |card| %>
        <%= link_to image_tag(card.image.url(:thumb)), card_path(card) %>
    <% end %>
    <br>
  <h4>ORACLE</h4>
  <p>Yoga master reverse osmosis light energy goddess kefir cosmic Dr. Bronner's, to end suffering life coach healing energy essential. Tantra holistic indigo child peacock feather, tapping seasonal. The buddha healer pranayama, forest prayer flags vitamin-rich tripping on enneagram. Bioneers ganesh goji berries, entheogen short-grain brown rice.</p>
    <% @oracle_minor.each do |card| %>
        <%= link_to image_tag(card.image.url(:thumb)), card_path(card) %>
    <% end %>
    <br><br><br><br><br>
</div>

app/views/nasas/index.html.erb
<br><br>
<div class="well">
  <%= image_tag("tarots2.jpg", :alt => "psychic", :class => "style_image") %>
</div>
<p>A single card reading can be an easy way to start the day. It can also be a learning tool, to start learning the deck. Whatver the cards have to reveal to you, just spend a moment on the imagery and meaning. Below is a tarot card, along with NASA's picture of the day. By considering the juxtapostion of these two cards together we can contemplate our place in it all.</p>
<br>
<div id="one-a-day">
  <div class="row">
    <div class="col s6">
      <h3>Tech Tarot</h3>
      <h4>Card of the Day</h4>
      <p><strong><%= link_to @card.card_name, card_path(@card) %></strong></p>
      <p><%= image_tag @card.image.url(:medium) %></p>
      <br>
      <div id="card_info">
        <p><%= @card.card_content %></p>
      </div>
    </div>
    <div class="col s6">
      <h3><%= link_to "NASA", "https://apod.nasa.gov/apod/astropix.html", :target => "_blank" %></h3>
      <h4>Photo of the Day</h4>
      <h6><%= @nasa_info["date"] %> <%= @nasa_info["title"] %></h6>
      <%= image_tag @nasa_info["url"], :id => "nasa_image" %>
      <br><br>
      <div id="nasa_info">
        <p><%= @nasa_info["explanation"] %></p>
      </div>
  </div>
</div>
<%= button_to "Descriptions", { :action => "new" }, :method => :get, remote: true  %>


<br><br><br><br><br><br><br>

app/views/nasas/new.js.erb
$('#nasa_info').toggle();
$('#card_info').toggle();

app/views/pages/search.html.erb
<div class="row">
  <% @results.each do |result| %>
  <div class="col s4">
    <h6><%= image_tag result.image.url(:large) %></h6>
  </div>
  <div class="col s8">
    <h1><%= result.card_name %></h1>
    <h6><%= result.card_content %></h6>
  </div>
  <% end %>
</div>

app/views/readings/index.html.erb
<br><br>
<div id="reading">
  <p>How to understand your reading</p>
  <br>
  <div class="well">
    <%= image_tag("geo.gif", :alt => "flower", :id => "geo_card") %>
  </div>
  <p>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Clatss aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a</p>
</div>

<div id="btn">
  <a onclick="$('#reading-cards, #refresh-cards').toggle();">Show me my Reading</a>
</div>

<div id="reading-cards" style="display:none;">
  <%= render "cards/three" %>
</div>
<br><br><br><br><br><br>
<div id="btn">
  <div id="refresh-cards" style="display:none;">
    <%= link_to 'New Reading', readings_path %>
  </div>
</div>
<br><br><br>